---
- hosts: multipass
  become: true

  tasks:
  - name: Copy deployment file
    copy:
      src: /mnt/c/users/bzs/workspace/ansible/httpd-deploy.yml
      dest: /home/ansible/httpd-deploy.yml

  - name: Copy service file
    copy:
      src: /mnt/c/users/bzs/workspace/ansible/httpd-service.yml
      dest: /home/ansible/httpd-service.yml

  - name: Copy index.html file
    copy:
      src: /mnt/c/users/bzs/workspace/ansible/index.html
      dest: /home/ansible/index.html

  - name: Configfile
    shell: microk8s kubectl create configmap index.html --from-file=index.html

  - name: Deployment
    shell: microk8s kubectl apply -f httpd-deploy.yml

  - name: Exposing service
    shell: microk8s kubectl apply -f httpd-service.yml