---
- hosts: multipass

  vars:
    helm_chart_url: "https://charts.bitnami.com/bitnami"
    helm_chart_url_2: "https://charts.helm.sh/stable"

  tasks:
  - name: Add apt-key for helm
    shell: curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -

  - name: Install apt-transport-https
    become: yes
    apt:
      name: apt-transport-https
      update_cache: yes

  - name: Write list file
    command: echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

  - name: Update cache
    become: yes
    apt:
      update_cache: yes

  - name: Install Helm
    become: yes
    apt:
      name: helm

  - name: Add bitnami repo
    become_user: ansible
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: "{{ helm_chart_url }}"

  - name: Add stable repo
    become_user: ansible
    kubernetes.core.helm_repository:
      name: stable
      repo_url: "{{ helm_chart_url_2 }}"

  - name: Create directory for Apache
    become: yes
    file:
      path: /home/{{ ansible_user }}/ansible/web
      state: directory

  - name: Copy index2.html file
    copy:
      src: /mnt/c/users/bzs/workspace/ansible/index2.html
      dest: /home/{{ ansible_user }}/ansible/web/index.html
    become: yes

  - name: Add index.html to ConfigMap
    shell: microk8s kubectl create configmap apache --from-file=/home/{{ ansible_user }}/ansible/web/index.html
    become: yes

  - name: Install Apache server
    shell: helm install test bitnami/apache --set service.type=NodePort --set htdocsConfigMap=apache