apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: example1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31802