---
- hosts: multipass
  become: yes
  vars:
    prometheus_staging_directory: "/home/{{ ansible_user }}/ansible/temp"

  tasks:
  - name: Move prometheus.yml to /etc/prometheus
    copy:
      src: /mnt/c/users/bzs/workspace/ansible/prometheus.yml
      dest: /etc/prometheus/

  - name: Start & enable Prometheus service
    systemd:
      daemon_reload: yes
      state: restarted
      name: prometheus
      enabled: yes
